---
title: "Joshua Cervantes y Daniel Sabater; Laboratorio 1"
author: "Joshua Cervantes y Daniel Sabater"
date: "24/4/2021"
output:
  pdf_document: default

---

Primero se cargan los paquetes y los datos
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(readxl)
library(tidyverse)
library(lubridate)
library(kableExtra)

Bono1 <- read_excel("Ex1.BonoPL.xlsx",
                    col_names = FALSE)
Bono2 <- read_excel("Ex1.BonoPL.xlsx", sheet = "Bond (2)",
                    col_names = FALSE)
Bono3 <- read_excel("Ex1.BonoPL.xlsx", sheet = "Bond (3)",
                    col_names = FALSE)
Bono4 <- read_excel("Ex1.BonoPL.xlsx", sheet = "Bond (4)",
                    col_names = FALSE)


Datos <- Bono1[c(2)]
Datos <- Datos[c(1:10), ]
Datos <- as.data.frame(t(Datos))
colnames(Datos)[1:length(Datos)] <-
  c(
    "ISIN",
    "TICKER",
    "Vencimiento",
    "Cupón(%)",
    "Frequencia cupón",
    "Monto",
    "Subcupon",
    "Liquid (SETT)",
    "Yield de entrada",
    "Precio Compra"
  )

```

#Funciones que se van a emplear
```{r}
vectorr <- c()
calculo_precio <-
  function(facial, cupon, tasa, periodos, dias, final) {
    for (i in 1:length(fecha)) {
      if (fecha[i] - fecha_pago[1] >= fecha_pago[2] - fecha_pago[1]) {
        fecha_pago <- fecha_pago[-1]
      }
      if (0 < as.numeric(final - fecha[i])) {
        A <- as.numeric(fecha[i] - fecha_pago[1])
        E <- dias / periodos
        Dsc <- E - A
        tasa_efectiva <- tasa[i] / (periodos * 100)
        N <- length(fecha_pago) - 2
        c <- length(fecha_pago) - c(2:length(fecha_pago))
        cupon_p <- cupon / periodos
        if(N==0){
         t_1<-facial*cupon_p+facial 
         t_2<-tasa_efectiva*Dsc/E+1
         t_3<-facial*A/E*cupon_p
         vectorr[i]<-t_1/t_2-t_3
        }else{
        vectorr[i] <- (
          facial * (1 + tasa_efectiva) ^ (-N - Dsc / E) + facial * cupon_p * sum((1 +
                                                                                    tasa_efectiva) ^ (-c - Dsc / E)) - facial * cupon_p * A / E
        )}
      } else{
        vectorr[i] <- facial
      }
    }
    
    return(vectorr)
  }
creacion_de_columnas <-
  function(interes,
           interes2,
           yas_bond_yld,
           G_capital,
           shock,
           TOTAL,
           Retorno_total,
           YAS_BOND_PX) {
    for (i in 1:(length(fecha) - 1)) {
      if (interes[i] < interes[i + 1]) {
        interes2[i + 1] <- interes2[i] + interes[i + 1] - interes[i]
      } else {
        interes2[i + 1] <-
          interes2[i] + interes[i + 1] - interes[i] + as.numeric(as.character(Datos$Subcupon))
      }#se calcula la columna de INT_ACC
      
      yas_bond_yld[i + 1] <- yas_bond_yld[i] - shock[i]
      G_capital <-
        c(G_capital,
          (YAS_BOND_PX[i + 1] - as.numeric(as.character(
            Datos$`Precio Compra`
          ))) *
            as.numeric(as.character(Datos$Monto)) / 100)
      TOTAL <- c(TOTAL, interes2[i] + G_capital[i])
      Retorno_total <-
        c(Retorno_total, TOTAL[i] / as.numeric(as.character(Datos$Monto)) * 100)
      if (i == (length(fecha) - 1)) {
        TOTAL <- c(TOTAL, interes2[i + 1] + G_capital[i + 1])
        Retorno_total <- c(Retorno_total
                           ,
                           TOTAL[i + 1] / as.numeric(as.character(Datos$Monto)) * 100)
      }
    }
    return(list(
      interes,
      interes2,
      yas_bond_yld,
      G_capital,
      shock,
      TOTAL,
      Retorno_total
    ))
  }
```

#Para bono 1
```{r}
fecha <- seq(as.Date("2019-03-15"), as.Date("2021-03-01"), "day")
fecha <- fecha[1 < wday(fecha) & wday(fecha) < 7]

interes1_1 <- as.numeric(Bono1$...2[-c(1:15)])
interes1_2 <- (0:(length(interes1_1) - 1))

factor_lineal<--(as.numeric(as.character(Datos$`Yield de entrada`))-as.numeric(as.character(Bono1[3,5])))/as.numeric(as.Date("2020-03-14")-as.Date("2019-03-15"))
ShockF_1<-c(factor_lineal)
ShockF_1<-c(ShockF_1,ShockF_1*as.numeric(fecha[-1]-fecha[-length(fecha)]))
YAS_BOND_YLD_1 <- c(2.458612, rep(0, length(interes1_1) - 1))
for (i in 2:length(YAS_BOND_YLD_1)) {
  YAS_BOND_YLD_1[i] <- YAS_BOND_YLD_1[i - 1] + ShockF_1[i - 1]
}

Gcapital_1 <- c(0)
TOTAL_1 <- c()
Retorno_total_1 <- c()


fecha_pago <- as.Date("2019-02-28")
j <- as.Date("2019-02-28")
while (j + 180 <= as.Date("2021-02-28")) {
  fecha_pago <-
    c(fecha_pago, ceiling_date(j + 180, unit = "month") - 1)
  j = j + 180
}

YAS_BOND_PX_1 <-
  calculo_precio(100, 0.025, YAS_BOND_YLD_1, 2, 360, as.Date("2021-02-28"))

bono_1 <-
  creacion_de_columnas(
    interes1_1,
    interes1_2,
    YAS_BOND_YLD_1,
    Gcapital_1 ,
    ShockF_1,
    TOTAL_1,
    Retorno_total_1,
    YAS_BOND_PX_1
  )
names(bono_1) <-
  c(
    "interes1_1",
    "interes1_2",
    "YAS_BOND_YLD_1",
    "Gcapital_1",
    "ShockF_1",
    "TOTAL_1",
    "Retorno_total_1"
  )
bono1 <-
  data.frame(
    "Fecha de evaluación" = fecha,
    "INT_ACC 1" = bono_1$interes1_1,
    "INT_ACC 1" = bono_1$interes1_2,
    bono_1$YAS_BOND_YLD_1,
    bono_1$ShockF_1,
    YAS_BOND_PX_1,
    bono_1$Gcapital_1,
    bono_1$TOTAL_1,
    bono_1$Retorno_total_1
  )


```


#Para bono 2
```{r}
fecha <- seq(as.Date("2019-03-15"), as.Date("2021-03-01"), "day")
fecha <- fecha[1 < wday(fecha) & wday(fecha) < 7]

interes2_1 <- as.numeric(Bono3$...2[-c(1:15)])
interes2_2 <- (0:(length(interes2_1) - 1))
ShockF_2 <- rep(0, length(interes2_1))
YAS_BOND_YLD_2 <- c(2.458612, rep(0, length(interes2_1) - 1))
for (i in 2:length(YAS_BOND_YLD_2)) {
  YAS_BOND_YLD_2[i] <- YAS_BOND_YLD_2[i - 1] + ShockF_2[i - 1]
}

Gcapital_2 <- c(0)
TOTAL_2 <- c()
Retorno_total_2 <- c()


fecha_pago <- as.Date("2019-02-28")
j <- as.Date("2019-02-28")
while (j + 180 <= as.Date("2021-02-28")) {
  fecha_pago <-
    c(fecha_pago, ceiling_date(j + 180, unit = "month") - 1)
  j = j + 180
}

YAS_BOND_PX_2 <-
  calculo_precio(100, 0.025, YAS_BOND_YLD_2, 2, 360, as.Date("2021-02-28"))

bono_2 <-
  creacion_de_columnas(
    interes2_1,
    interes2_2,
    YAS_BOND_YLD_2,
    Gcapital_2 ,
    ShockF_2,
    TOTAL_2,
    Retorno_total_2,
    YAS_BOND_PX_2
  )
names(bono_2) <-
  c(
    "interes2_1",
    "interes2_2",
    "YAS_BOND_YLD_2",
    "Gcapital_2",
    "ShockF_2",
    "TOTAL_2",
    "Retorno_total_2"
  )
bono2 <-
  data.frame(
    "Fecha de evaluación" = fecha,
    "INT_ACC 1" = bono_2$interes2_1,
    "INT_ACC 2" = bono_2$interes2_2,
    bono_2$YAS_BOND_YLD_2,
    bono_2$ShockF_2,
    YAS_BOND_PX_2,
    bono_2$Gcapital_2,
    bono_2$TOTAL_2,
    bono_2$Retorno_total_2
  )


```






#Bono 3


```{r}

fecha <- seq(as.Date("2019-03-15"), as.Date("2021-03-01"), "day")
fecha <- fecha[1 < wday(fecha) & wday(fecha) < 7]

interes3_1 <- as.numeric(Bono3$...2[-c(1:15)])
interes3_2 <- (0:(length(interes3_1) - 1))

ShockF_3 <- as.numeric(Bono3$...6[-c(1:15)])
YAS_BOND_YLD_3 <- c(2.458612, rep(0, length(interes2_1) - 1))
for (i in 2:length(YAS_BOND_YLD_3)) {
  YAS_BOND_YLD_3[i] <- YAS_BOND_YLD_3[i - 1] + ShockF_3[i - 1]
}

Gcapital_3 <- c(0)
TOTAL_3 <- c()
Retorno_total_3 <- c()


fecha_pago <- as.Date("2019-02-28")
j <- as.Date("2019-02-28")
while (j + 180 <= as.Date("2021-02-28")) {
  fecha_pago <-
    c(fecha_pago, ceiling_date(j + 180, unit = "month") - 1)
  j = j + 180
}
vectorr <- c()
YAS_BOND_PX_3 <-
  calculo_precio(100, 0.025, YAS_BOND_YLD_3, 2, 360, as.Date("2021-02-28"))

bono_3 <-
  creacion_de_columnas(
    interes3_1,
    interes3_2,
    YAS_BOND_YLD_3,
    Gcapital_3 ,
    ShockF_3,
    TOTAL_3,
    Retorno_total_3,
    YAS_BOND_PX_3
  )
names(bono_3) <-
  c(
    "interes3_1",
    "interes3_2",
    "YAS_BOND_YLD_3",
    "Gcapital_3",
    "ShockF_3",
    "TOTAL_3",
    "Retorno_total_3"
  )
bono3 <-
  data.frame(
    "Fecha de evaluación" = fecha,
    "INT_ACC 1" = bono_3$interes3_1,
    "INT_ACC 2" = bono_3$interes3_2,
    bono_3$YAS_BOND_YLD_3,
    bono_3$ShockF_3,
    YAS_BOND_PX_3,
    bono_3$Gcapital_3,
    bono_3$TOTAL_3,
    bono_3$Retorno_total_3
  )

```



#Bono 4


```{r}
fecha <- seq(as.Date("2019-03-15"), as.Date("2021-03-01"), "day")
fecha <- fecha[1 < wday(fecha) & wday(fecha) < 7]

interes4_1 <- as.numeric(Bono4$...2[-c(1:15)])
interes4_2 <- (0:(length(interes4_1) - 1))

ShockF_4 <- as.numeric(Bono4$...6[-c(1:15)])
YAS_BOND_YLD_4 <- c(2.458612, rep(0, length(interes2_1) - 1))
for (i in 2:length(YAS_BOND_YLD_4)) {
  YAS_BOND_YLD_4[i] <- YAS_BOND_YLD_4[i - 1] + ShockF_4[i - 1]
}

Gcapital_4 <- c(0)
TOTAL_4 <- c()
Retorno_total_4 <- c()
fecha_pago <- as.Date("2019-02-28")
j <- as.Date("2019-02-28")
while (j + 180 <= as.Date("2021-02-28")) {
  fecha_pago <-
    c(fecha_pago, ceiling_date(j + 180, unit = "month") - 1)
  j = j + 180
}
vectorr <- c()
YAS_BOND_PX_4 <-
  calculo_precio(100, 0.025, YAS_BOND_YLD_4, 2, 360, as.Date("2021-02-28"))
bono_4 <-
  creacion_de_columnas(
    interes4_1,
    interes4_2,
    YAS_BOND_YLD_4,
    Gcapital_4 ,
    ShockF_4,
    TOTAL_4,
    Retorno_total_4,
    YAS_BOND_PX_4
  )
names(bono_4) <-
  c(
    "interes4_1",
    "interes4_2",
    "YAS_BOND_YLD_4",
    "Gcapital_4",
    "ShockF_4",
    "TOTAL_4",
    "Retorno_total_4"
  )
bono4 <-
  data.frame(
    "Fecha de evaluación" = fecha,
    "INT_ACC 1" = bono_4$interes4_1,
    "INT_ACC 2" = bono_4$interes4_2,
    bono_4$YAS_BOND_YLD_4,
    bono_4$ShockF_4,
    YAS_BOND_PX_4,
    bono_4$Gcapital_4,
    bono_4$TOTAL_4,
    bono_4$Retorno_total_4
  )

hola

```










